In [1]:
########################################################################
### The code in this cell works only with TensorFlow 1.x
########################################################################

# import tensorflow as tf

# # Create TensorFlow object called tensor
# hello_constant = tf.constant('Hello World!')

# with tf.Session() as sess:
#     # Run the tf.constant operation in the session
#     output = sess.run(hello_constant)
#     print(output)

In [2]:
# TensorFlow 2.1 installed
# import tensorflow as tf
# tf.compat.v1.disable_eager_execution()

# Tensorflow 1 compatibility
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.compat.v1.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

    output_dc = output.decode()
    print(output_dc)


Instructions for updating:
non-resource variables are not supported in the long term
b'Hello World!'
Hello World!


In [3]:
# Using feed_dict
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})
    
print(output)

Hello World


In [4]:
# Using feed_dict with multiple tensors
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output)


Test String


In [5]:
# Math
x = tf.add(5, 2)  # 7
y = tf.subtract(10, 4) # 6
z = tf.multiply(2, 5)  # 10

with tf.Session() as sess:
    outputx = sess.run(x)
    outputy = sess.run(y)
    outputz = sess.run(z)
    print(outputx)
    print(outputy)
    print(outputz)

7
6
10


In [6]:
# Type casting
x = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # 1

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

1


In [7]:
# Variables
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    
# Generate random numbers from a normal distribution.
# Randomizing the weights helps the model from becoming stuck in the same place every time it is trained.
# The tf.truncated_normal() function returns a tensor with random values from a normal distribution 
# whose magnitude is no more than 2 standard deviations from the mean. 
# Use the simplest solution, setting the bias to 0.
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
bias = tf.Variable(tf.zeros(n_labels))


In [8]:
import numpy as np
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
u = np.array([1, 2, 3])
print(t + u)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [9]:
def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    return np.exp(x) / np.sum(np.exp(x), axis=0)

logits = [3.0, 1.0, 0.2]
print(softmax(logits))

# logits is a one-dimensional array with 3 elements
logits = [1.0, 2.0, 3.0]
# softmax will return a one-dimensional array with 3 elements
print(softmax(logits))


[0.8360188  0.11314284 0.05083836]
[0.09003057 0.24472847 0.66524096]


In [10]:
# Tensorflow Softmax function -- does not require softmax() function above
x = tf.nn.softmax([2.0, 1.0, 0.2])
with tf.Session() as sess:
    output = sess.run(x)
    print(output)

[0.65223986 0.23994564 0.10781453]


In [11]:
# Solution is available in the other "solution.ipynb" 
# import tensorflow as tf


def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)    
    
    with tf.Session() as sess:
        pass
        # TODO: Feed in the logit data
        # output = sess.run(softmax,    )
        output = sess.run(softmax, feed_dict={logits: logit_data})
#         print(output)

    return output

print(run())

[0.6590012  0.24243298 0.09856589]


In [12]:
from tensorflow.examples.tutorials.mnist import input_data
# import tensorflow as tf
# tensorflow_datasets.load('mnist')
# tf.keras.datasets.mnist.load_data(path='mnist.npz')


n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
# mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)
mnist = input_data.read_data_sets('/tmp/tensorflow/mnist/input_data', one_hot=True)


# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])



Instructions for updating:
Please use alternatives such as: tensorflow_datasets.load('mnist')
Instructions for updating:
Please write your own downloading logic.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/_DataS

In [13]:
### Quiz 1: Minibatch ###

#from tensorflow.examples.tutorials.mnist import input_data
# import tensorflow as tf
# import numpy as np

### from helper import batches ###
import math

def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    # TODO: Implement batching
    output_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        output_batches.append(batch)
        
    return output_batches



# from quiz import batches
from pprint import pprint

# 4 Samples of features
example_features = [
    ['F11','F12','F13','F14'],
    ['F21','F22','F23','F24'],
    ['F31','F32','F33','F34'],
    ['F41','F42','F43','F44']]
# 4 Samples of labels
example_labels = [
    ['L11','L12'],
    ['L21','L22'],
    ['L31','L32'],
    ['L41','L42']]

# PPrint prints data structures like 2d arrays, so they are easier to read
pprint(batches(3, example_features, example_labels))


[[[['F11', 'F12', 'F13', 'F14'],
   ['F21', 'F22', 'F23', 'F24'],
   ['F31', 'F32', 'F33', 'F34']],
  [['L11', 'L12'], ['L21', 'L22'], ['L31', 'L32']]],
 [[['F41', 'F42', 'F43', 'F44']], [['L41', 'L42']]]]


In [14]:
### Quiz 2: Minibatch ###
### imports already imported or defined ###
# from tensorflow.examples.tutorials.mnist import input_data
# import tensorflow as tf
# import numpy as np
# from helper import batches

learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
##### Udacity
# mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)
##### Local computer
mnist = input_data.read_data_sets('/tmp/tensorflow/mnist/input_data', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

################

# TODO: Set batch size
batch_size = 128
assert batch_size is not None, 'You must set the batch size'

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    
    # TODO: Train optimizer on all batches
    for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        sess.run(optimizer, feed_dict={features: batch_features, labels: batch_labels})

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Test Accuracy: 0.10199999809265137


In [15]:
# import tensorflow as tf
# print (tf .__file__)
# from tensorflow.examples.tutorials.mnist import input_data
# print(input_data.__file__)

Epochs

An epoch is a single forward and backward pass of the whole dataset. This is used to increase the accuracy of the model without requiring more data. This section will cover epochs in TensorFlow and how to choose the right number of epochs.

The following TensorFlow code trains a model using 10 epochs.

In [18]:
# from tensorflow.examples.tutorials.mnist import input_data
# import tensorflow as tf
# import numpy as np
# from helper import batches  # Helper function created in Mini-batching section


def print_epoch_stats(epoch_i, sess, last_features, last_labels):
    """
    Print cost and validation accuracy of an epoch
    """
    current_cost = sess.run(
        cost,
        feed_dict={features: last_features, labels: last_labels})
    valid_accuracy = sess.run(
        accuracy,
        feed_dict={features: valid_features, labels: valid_labels})
    print('Epoch: {:<4} - Cost: {:<8.3} Valid Accuracy: {:<5.3}'.format(
        epoch_i,
        current_cost,
        valid_accuracy))

n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
##### Udacity
# mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)
##### Local computer
mnist = input_data.read_data_sets('/tmp/tensorflow/mnist/input_data', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
valid_features = mnist.validation.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
valid_labels = mnist.validation.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
learning_rate = tf.placeholder(tf.float32)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

init = tf.global_variables_initializer()

batch_size = 128
epochs = 100
learn_rate = 0.001

train_batches = batches(batch_size, train_features, train_labels)

with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch_i in range(epochs):

        # Loop over all batches
        for batch_features, batch_labels in train_batches:
            train_feed_dict = {
                features: batch_features,
                labels: batch_labels,
                learning_rate: learn_rate}
            sess.run(optimizer, feed_dict=train_feed_dict)

        # Print cost and validation accuracy of an epoch
        print_epoch_stats(epoch_i, sess, batch_features, batch_labels)

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))

Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
Epoch: 0    - Cost: 12.6     Valid Accuracy: 0.0902
Epoch: 1    - Cost: 10.6     Valid Accuracy: 0.097
Epoch: 2    - Cost: 9.37     Valid Accuracy: 0.108
Epoch: 3    - Cost: 8.57     Valid Accuracy: 0.124
Epoch: 4    - Cost: 8.02     Valid Accuracy: 0.145
Epoch: 5    - Cost: 7.63     Valid Accuracy: 0.162
Epoch: 6    - Cost: 7.32     Valid Accuracy: 0.18 
Epoch: 7    - Cost: 7.06     Valid Accuracy: 0.2  
Epoch: 8    - Cost: 6.83     Valid Accuracy: 0.221
Epoch: 9    - Cost: 6.61     Valid Accuracy: 0.239
Epoch: 10   - Cost: 6.4      Valid Accuracy: 0.257
Epoch: 11   - Cost: 6.21     Valid Accuracy: 0.276
Epoch: 12   - Cost: 6.03     Valid Accuracy: 0.292
Epoch: 13   - Cost: 5.86     Valid Accuracy: 0.308
Epo

TensorFlow lab at ~/workspace/udacity/CarND-TensorFlow-Lab/